# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auction_pb2 as auction__pb2


class BuyerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.announce_price = channel.unary_unary(
                '/auction.BuyerService/announce_price',
                request_serializer=auction__pb2.AnnouncePriceRequest.SerializeToString,
                response_deserializer=auction__pb2.SuccessMessage.FromString,
                )
        self.finish_auction = channel.unary_unary(
                '/auction.BuyerService/finish_auction',
                request_serializer=auction__pb2.FinishAuctionRequest.SerializeToString,
                response_deserializer=auction__pb2.SuccessMessage.FromString,
                )


class BuyerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def announce_price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def finish_auction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'announce_price': grpc.unary_unary_rpc_method_handler(
                    servicer.announce_price,
                    request_deserializer=auction__pb2.AnnouncePriceRequest.FromString,
                    response_serializer=auction__pb2.SuccessMessage.SerializeToString,
            ),
            'finish_auction': grpc.unary_unary_rpc_method_handler(
                    servicer.finish_auction,
                    request_deserializer=auction__pb2.FinishAuctionRequest.FromString,
                    response_serializer=auction__pb2.SuccessMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.BuyerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def announce_price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction.BuyerService/announce_price',
            auction__pb2.AnnouncePriceRequest.SerializeToString,
            auction__pb2.SuccessMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def finish_auction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction.BuyerService/finish_auction',
            auction__pb2.FinishAuctionRequest.SerializeToString,
            auction__pb2.SuccessMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SellerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.withdraw = channel.unary_unary(
                '/auction.SellerService/withdraw',
                request_serializer=auction__pb2.UserAuctionPair.SerializeToString,
                response_deserializer=auction__pb2.SuccessMessage.FromString,
                )


class SellerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.withdraw,
                    request_deserializer=auction__pb2.UserAuctionPair.FromString,
                    response_serializer=auction__pb2.SuccessMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.SellerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SellerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction.SellerService/withdraw',
            auction__pb2.UserAuctionPair.SerializeToString,
            auction__pb2.SuccessMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PlatformServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rpc_platform_serve = channel.unary_unary(
                '/auction.PlatformService/rpc_platform_serve',
                request_serializer=auction__pb2.PlatformServiceRequest.SerializeToString,
                response_deserializer=auction__pb2.PlatformServiceResponse.FromString,
                )


class PlatformServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def rpc_platform_serve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'rpc_platform_serve': grpc.unary_unary_rpc_method_handler(
                    servicer.rpc_platform_serve,
                    request_deserializer=auction__pb2.PlatformServiceRequest.FromString,
                    response_serializer=auction__pb2.PlatformServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.PlatformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlatformService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def rpc_platform_serve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction.PlatformService/rpc_platform_serve',
            auction__pb2.PlatformServiceRequest.SerializeToString,
            auction__pb2.PlatformServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
