# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\x12\x07\x61uction\"7\n\x0fUserAuctionPair\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nauction_id\x18\x02 \x01(\t\"w\n\x14\x41nnouncePriceRequest\x12\x12\n\nauction_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x03\x12*\n\x0c\x62uyer_status\x18\x04 \x03(\x0b\x32\x14.auction.BuyerStatus\"~\n\x14\x46inishAuctionRequest\x12\x12\n\nauction_id\x18\x01 \x01(\t\x12\x17\n\x0fwinner_username\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x03\x12*\n\x0c\x62uyer_status\x18\x04 \x03(\x0b\x32\x14.auction.BuyerStatus\"&\n\x16PlatformServiceRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\":\n\x17PlatformServiceResponse\x12\x11\n\tis_leader\x18\x01 \x01(\x08\x12\x0c\n\x04json\x18\x02 \x01(\t\"2\n\x0eSuccessMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0b\x42uyerStatus\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x32\xa2\x01\n\x0c\x42uyerService\x12H\n\x0e\x61nnounce_price\x12\x1d.auction.AnnouncePriceRequest\x1a\x17.auction.SuccessMessage\x12H\n\x0e\x66inish_auction\x12\x1d.auction.FinishAuctionRequest\x1a\x17.auction.SuccessMessage2N\n\rSellerService\x12=\n\x08withdraw\x12\x18.auction.UserAuctionPair\x1a\x17.auction.SuccessMessage2j\n\x0fPlatformService\x12W\n\x12rpc_platform_serve\x12\x1f.auction.PlatformServiceRequest\x1a .auction.PlatformServiceResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERAUCTIONPAIR._serialized_start=26
  _USERAUCTIONPAIR._serialized_end=81
  _ANNOUNCEPRICEREQUEST._serialized_start=83
  _ANNOUNCEPRICEREQUEST._serialized_end=202
  _FINISHAUCTIONREQUEST._serialized_start=204
  _FINISHAUCTIONREQUEST._serialized_end=330
  _PLATFORMSERVICEREQUEST._serialized_start=332
  _PLATFORMSERVICEREQUEST._serialized_end=370
  _PLATFORMSERVICERESPONSE._serialized_start=372
  _PLATFORMSERVICERESPONSE._serialized_end=430
  _SUCCESSMESSAGE._serialized_start=432
  _SUCCESSMESSAGE._serialized_end=482
  _BUYERSTATUS._serialized_start=484
  _BUYERSTATUS._serialized_end=531
  _BUYERSERVICE._serialized_start=534
  _BUYERSERVICE._serialized_end=696
  _SELLERSERVICE._serialized_start=698
  _SELLERSERVICE._serialized_end=776
  _PLATFORMSERVICE._serialized_start=778
  _PLATFORMSERVICE._serialized_end=884
# @@protoc_insertion_point(module_scope)
