# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x17\n\x07\x43ommand\x12\x0c\n\x04json\x18\x01 \x01(\t\"G\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\r\n\x05index\x18\x02 \x01(\x03\x12\x1e\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\r.raft.Command\"S\n\nPersistent\x12\x14\n\x0c\x63urrent_term\x18\x01 \x01(\x03\x12\x11\n\tvoted_for\x18\x02 \x01(\x05\x12\x1c\n\x04logs\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\"\x94\x01\n\nAE_Request\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\",\n\x0b\x41\x45_Response\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"_\n\nRV_Request\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"1\n\x0bRV_Response\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x32\x85\x01\n\x0bRaftService\x12;\n\x12rpc_append_entries\x12\x10.raft.AE_Request\x1a\x11.raft.AE_Response\"\x00\x12\x39\n\x10rpc_request_vote\x12\x10.raft.RV_Request\x1a\x11.raft.RV_Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=20
  _COMMAND._serialized_end=43
  _LOGENTRY._serialized_start=45
  _LOGENTRY._serialized_end=116
  _PERSISTENT._serialized_start=118
  _PERSISTENT._serialized_end=201
  _AE_REQUEST._serialized_start=204
  _AE_REQUEST._serialized_end=352
  _AE_RESPONSE._serialized_start=354
  _AE_RESPONSE._serialized_end=398
  _RV_REQUEST._serialized_start=400
  _RV_REQUEST._serialized_end=495
  _RV_RESPONSE._serialized_start=497
  _RV_RESPONSE._serialized_end=546
  _RAFTSERVICE._serialized_start=549
  _RAFTSERVICE._serialized_end=682
# @@protoc_insertion_point(module_scope)
